#!/bin/sh
#
# postrm - Copyright (c) 2018-2024 - Olivier Poncet
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# summary of how this script can be called:
#
# <postrm> `remove'
# <postrm> `purge'
# <old-postrm> `upgrade' <new-version>
# <new-postrm> `failed-upgrade' <old-version>
# <new-postrm> `abort-install'
# <new-postrm> `abort-install' <old-version>
# <new-postrm> `abort-upgrade' <old-version>
# <disappearer's-postrm> `disappear' <overwriter> <overwriter-version>

# ----------------------------------------------------------------------------
# abort on error
# ----------------------------------------------------------------------------

set -e

# ----------------------------------------------------------------------------
# variables
# ----------------------------------------------------------------------------

arg_command="${1}"

# ----------------------------------------------------------------------------
# purge
# ----------------------------------------------------------------------------

if [ "${arg_command}" = 'purge' ]
then
    exit 0
fi

# ----------------------------------------------------------------------------
# remove
# ----------------------------------------------------------------------------

if [ "${arg_command}" = 'remove' ]
then
    exit 0
fi

# ----------------------------------------------------------------------------
# upgrade
# ----------------------------------------------------------------------------

if [ "${arg_command}" = 'upgrade' ]
then
    exit 0
fi

# ----------------------------------------------------------------------------
# failed-upgrade
# ----------------------------------------------------------------------------

if [ "${arg_command}" = 'failed-upgrade' ]
then
    exit 0
fi

# ----------------------------------------------------------------------------
# abort-install
# ----------------------------------------------------------------------------

if [ "${arg_command}" = 'abort-install' ]
then
    exit 0
fi

# ----------------------------------------------------------------------------
# abort-upgrade
# ----------------------------------------------------------------------------

if [ "${arg_command}" = 'abort-upgrade' ]
then
    exit 0
fi

# ----------------------------------------------------------------------------
# disappear
# ----------------------------------------------------------------------------

if [ "${arg_command}" = 'disappear' ]
then
    exit 0
fi

# ----------------------------------------------------------------------------
# unknown argument
# ----------------------------------------------------------------------------

echo "postrm: unknown argument '${arg_command}'" >&2
exit 1

# ----------------------------------------------------------------------------
# End-Of-File
# ----------------------------------------------------------------------------
