#!/bin/sh
#
# postinst - Copyright (c) 2018-2024 - Olivier Poncet
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# summary of how this script can be called:
#
# <postinst> `configure' <most-recently-configured-version>
# <old-postinst> `abort-upgrade' <new version>
# <conflictor's-postinst> `abort-remove' `in-favour' <package> <new-version>
# <postinst> `abort-remove'
# <deconfigured's-postinst> `abort-deconfigure' `in-favour' <failed-install-package> <version> `removing' <conflicting-package> <version>

# ----------------------------------------------------------------------------
# abort on error
# ----------------------------------------------------------------------------

set -e

# ----------------------------------------------------------------------------
# variables
# ----------------------------------------------------------------------------

arg_command="${1}"

# ----------------------------------------------------------------------------
# configure
# ----------------------------------------------------------------------------

if [ "${arg_command}" = 'configure' ]
then
    exit 0
fi

# ----------------------------------------------------------------------------
# abort-upgrade
# ----------------------------------------------------------------------------

if [ "${arg_command}" = 'abort-upgrade' ]
then
    exit 0
fi

# ----------------------------------------------------------------------------
# abort-remove
# ----------------------------------------------------------------------------

if [ "${arg_command}" = 'abort-remove' ]
then
    exit 0
fi

# ----------------------------------------------------------------------------
# abort-deconfigure
# ----------------------------------------------------------------------------

if [ "${arg_command}" = 'abort-deconfigure' ]
then
    exit 0
fi

# ----------------------------------------------------------------------------
# unknown argument
# ----------------------------------------------------------------------------

echo "postinst: unknown argument '${arg_command}'" >&2
exit 1

# ----------------------------------------------------------------------------
# End-Of-File
# ----------------------------------------------------------------------------
